package valkyrie: unstable;

world unstable {
    import exports;
    import utf8;
    import integer;
}

interface printer {
    print-i8: func(value: s8);
    print-i16: func(value: s16);
    print-i32: func(value: s32);
    print-i64: func(value: s64);
    print-u8: func(value: u8);
    print-u16: func(value: u16);
    print-u32: func(value: u32);
    print-u64: func(value: u64);
    print-f32: func(value: float32);
    print-f64: func(value: float64);
    print-char: func(value: char);
    print-str: func(value: string);
}

interface utf8 {
    resource utf8-buffer {
        constructor(string: string);
        print: func();
    }
    resource utf8-view {
        constructor(string: string);
        print: func();
    }
}

interface integer {
    resource integer-buffer {
        print: func();
    }
    resource integer-view {
        print: func();
    }
}


